user_valid:
  max_email_length: 255
  max_name_length: 50
  min_pass_length: 6
remember_me: "1"
gravatar_imagine_size: 50
configure:
  email:
    owner: "noreply@example.com"
    reset: "to@example.com"
host: "localhost:3000"
password_reset_expire: 2
